### ISSUE TITLE
Technical Blog 3 - Arrays and Hashes

### ISSUE THREAD

**Issue by egarreau** [briankennedy1/briankennedy1.github.io#2]
Hi Brain,

I came across your blog post on the DBCArrayHash hashtag on twitter and really liked it, so I thought I would give you some feedback. Your explanation and examples were very clear, easy-to-follow, and interesting. I also liked the way you formatted the post, with the linebreaks between sections and the embedded gist for the hash (that's definitely a trick I'm going to steal!). One thing you could have done differently would be to more thoroughly explain the differences in the way you extract information from arrays versus hashes (for example, iterating over an array with a for loop), and how that affects when they're used. Overall, though, it looks great!

**Comment by briankennedy1** [comment]
Thanks for the feedback, Evangeline! Good call on the iteration and getting info out of the array.
